services:
  php:
    image: php:8.2-apache
    container_name: php-8.2-apache
    ports:
      - "9000:80"
    volumes:
      - ./public_html:/var/www/html
    build:
      context: .
      dockerfile: docker/php/Dockerfile
