# routes.yaml
event_it.public.homepage:
  path: /
  controller: App\Controller\Home\HomeController
  method: index
  
users:
  path: /users
  controller: UsersController
  method: index

contact:
  path: /contact
  controller: ContactController
  method: index

  # Here ajax's route
event_it.ajax.public.manage_cookie:
  path: /ajax/cookie
  controller: App\Cookie\CookieHandler
  method: handleRequest
